[functions]
  node_bundler = "esbuild"
  ignored_node_modules = ["ky-universal"]
  external_node_modules = ["jsdom"]
  
  [build]
    publish = "."
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "."
    node_bundler = "esbuild"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200